import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/redux/Providers';
import Provider from '@/components/Provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Provider>
        {children}
        </Provider>
        </body>
    </html>
    </Providers>
  )
}
